<?php
/**
 * Include other files necessary for this module
 */
module_load_include('inc', 'html_heads', 'html_heads.pagemaps');

/**
 * Process html head content
 * @return string
 */
function html_heads_process()
{

    $heads  = '';
    $path   = request_path();

    $heads .= html_heads_find('<all>');

    if (drupal_is_front_page()) {
        $heads .= html_heads_find('<front>');
    }
    elseif ($path != '' && !preg_match('/admin/', $path)) {

        $heads .= html_heads_find($path);
        $heads .= html_heads_pagemaps_process($path);
    }


    return $heads;

}

/**
 * Find html heads with the current path
 * @param $path
 * @return string
 */
function html_heads_find($path)
{
    $query = db_select('{node}', 'node');
    $query->fields('node', array('created'));
    $query->fields('field_data_body', array('body_value'));
    $query->leftJoin('{field_data_field_path}', 'field_data_field_path', 'node.nid = field_data_field_path.entity_id');
    $query->leftJoin('{field_data_body}', 'field_data_body', 'node.nid = field_data_body.entity_id');
    $query->condition('field_data_field_path.field_path_value', $path);
    $query->condition('node.type', array('html_head'), 'IN');
    $query->condition('node.status', 1);
    $query->orderBy('node.created', 'ASC');
    $results = $query->execute();

    $heads = '';

    foreach ($results AS $result) {
        $heads .= html_heads_parser($result->body_value);
    }

    return $heads;

}

/**
 * Find tokens and replace it
 * @param $html
 * @return mixed
 */
function html_heads_parser($html)
{
    $html = preg_replace('/\[current-date\]/', date('Y-m-d'), $html);

    return $html;
}