<?php


/**
 * Implements hook_rules_event_info();
 * @ingroup rules
 */
function bwd_crm_rules_event_info()
{

    $variables = array(
        'node' => array(
            'type' => 'node',
            'label' => t('Node'),
        ));


    $items['crm_expire'] = array(
        'label' => t('CRM clients expire actions'),
        'group' => t('Custom'),
        'variables' => $variables,
    );


    return $items;
}


/**
 * Implements hook_cron();
 */
function bwd_crm_cron()
{
    $query = db_select('{node}', 'node');
    $query->fields('node', array('nid'));
    $query->innerJoin('{field_data_field_expired}', 'field_data_field_expired', 'node.nid = field_data_field_expired.entity_id');
    $query->condition('node.status', 1);
    $query->condition('node.type', array('crm_client'), 'IN');
    $query->condition('field_data_field_expired.field_expired_value', 0);
    $results= $query->execute()->fetchAll();

    foreach ($results AS $result) {
        $node = node_load($result->nid);
        rules_invoke_event('crm_expire', $node);

    }
}

/**
 * If visitor isn't an admin, redirect to 403 page
 * @param $node
 * @param $view_mode
 * @param $langcode
 */
function bwd_crm_node_view($node, $view_mode, $langcode)
{
    if ($node->type == 'crm_client') {
        if (!user_has_role('crm')) {
            drupal_goto('403');
        }
    }
}


/**
 * Compare current date and expire date by client
 * @param $node
 * @return bool
 */
function bwd_crm_client_is_expired($node)
{
    if (date('Y-m', $node->field_expire_date[LANGUAGE_NONE][0]['value']) <= date('Y-m')) {
        return true;
    }
    else {
        return false;
    }
}

/**
 * Update expired status to Client of our CRM
 * @param $node
 */
function bwd_crm_client_set_expire_status($node)
{
    $node->field_expired[LANGUAGE_NONE][0]['value'] = '1';

    node_save($node);
    return $node;
}